// <auto-generated />
using System;
using EmployeeMicroservice.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeMicroservice.Db.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220125210434_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeMicroservice.Db.Model.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Signature = "Developers"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Signature = "Administration"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            ParentId = 1,
                            Signature = "HR department"
                        });
                });

            modelBuilder.Entity("EmployeeMicroservice.Db.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            IsDeleted = false,
                            Name = "Egor",
                            Patronymic = "Viktotovich",
                            Surname = "Koshel"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            IsDeleted = false,
                            Name = "TestName",
                            Patronymic = "TestPatronymic",
                            Surname = "TestSurname"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            IsDeleted = false,
                            Name = "TestName1",
                            Patronymic = "TestPatronymic1",
                            Surname = "TestSurname1"
                        });
                });

            modelBuilder.Entity("EmployeeMicroservice.Db.Model.Department", b =>
                {
                    b.HasOne("EmployeeMicroservice.Db.Model.Department", "Parent")
                        .WithMany("Departments")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EmployeeMicroservice.Db.Model.Employee", b =>
                {
                    b.HasOne("EmployeeMicroservice.Db.Model.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeMicroservice.Db.Model.Department", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
